### ISSUE TITLE
Trade

### ISSUE THREAD

**Issue by C13L0** [Mephiles/torntools_2#180]
**Travel information**
* [x] Display item values. Added by #190 .
* [x] Display total trade value. Added by #190 .
* [x] Add 'open chat' button. Added by #190 .
* [ ] Remove confirmation message when accepting trades
